---
- hosts: all
  sudo: yes
  gather_facts: no

  tasks:

  - name: get app requirements
    apt: name={{item}} state=installed update_cache=yes
    with_items:
        - python
        - python-pip
        - python-virtualenv
        - nginx
        - gunicorn
        - supervisor
        - git

