---
- hosts: web
  sudo: yes
  gather_facts: no

  tasks:

  - name: get app requirements
    apt: name={{ item }} state=installed update_cache=yes
    with_items:
        - python
        - python-pip
        - python-virtualenv
        - nginx
        - gunicorn
        - supervisor
        - git

  - name: create project dir
    file: path=/home/www state=directory mode=0755
    tags:
        - flask

  - name: create virtualenv
    command: /usr/bin/virtualenv /home/www/env
    tags:
        - flask

  - name: add virtualenv libs location to $PYTHONPATH
  #lineinfile: dest=/home/vagrant/.profile line="PYTHONPATH=$PYTHONPATH:/home/www/env/lib/python2.7/site-packages" state=present
    lineinfile: dest=/etc/environment line="PYTHONPATH=$PYTHONPATH:/home/www/env/lib/python2.7/site-packages" state=present
    tags:
        - flask

  - name: install Flask
    command: /home/www/env/bin/pip install Flask
    tags:
        - flask
  
  - name: link app directory
    file: src=/vagrant/flask_project dest=/home/www/flask_project state=link
    tags:
        - flask

  - name: remove the default nginx config file
    file: path=/etc/nginx/sites-enabled/default state=absent
    tags:
        - nginx

  - name: create a new nginx config file
    template: src=/vagrant/config/flask_project dest=/etc/nginx/sites-available/flask-project
    tags:
        - nginx

  - name: symlink the new config file
    file: src=/etc/nginx/sites-available/flask-project dest=/etc/nginx/sites-enabled/flask-project state=link
    notify: restart nginx
    tags:
        - nginx

  - name: create a new supervisor config file
    template: src=/vagrant/config/flask_project.conf dest=/etc/supervisor/conf.d/flask_project.conf
    tags:
        - supervisor

  - name: create a bare repo dir
    file: path=/home/git state=directory mode=0755
    tags:
        - repo

  - name: init a bare Git repo
    command: git init --bare /home/git/flask_project.git
    tags:
        - repo

  - name: create a post-receive hook
    template: src=/vagrant/config/post-receive dest=/home/git/flask_project.git/hooks/post-receive mode=0755
    tags:
        - repo

  - name: init a working copy Git repo
    command: git init /home/www/flask_project/
    tags:
        - repo

  - name: add a production remote to working copy repo
    #git: repo=root@10.10.32.21:/home/git/flask_project.git dest=/home/www/flask_project remote=production accept_hostkey=yes
    command: git remote add production vagrant@10.10.32.21:/home/git/flask_project.git chdir=/home/www/flask_project
    tags:
        - repo


  handlers:

  - name: restart nginx
    service: name=nginx state=restarted

