---
- hosts: web
  sudo: yes
  gather_facts: no

  tasks:


  - name: create a bare repo dir
    file: path=/home/git/flask_project.git state=directory mode=0755
    tags:
        - repo

  - name: init a bare Git repo
    command: git init --bare chdir=/home/git/flask_project.git
    tags:
        - repo

  - name: change bare repo dir ownership
    file: path=/home/git/flask_project.git state=directory owner=vagrant group=vagrant mode=0755 recurse=yes
    tags:
        - repo

  - name: create a post-receive hook
    template: src=/vagrant/config/post-receive dest=/home/git/flask_project.git/hooks/post-receive owner=vagrant group=vagrant mode=0755
    tags:
        - repo

  - name: init a working copy Git repo
    command: git init /home/www/flask_project/
    tags:
        - repo
