---
- hosts: all
  sudo: yes
  gather_facts: no
  remote_user: vagrant
  roles:
    - common

- hosts: production
  sudo: yes
  gather_facts: no
  roles:
    - base
    - flask
    - nginx 
    - supervisor 
