# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  # mgmt
  config.vm.define "mgmt" do |mgmt_config|
      mgmt_config.vm.box = "ubuntu/trusty64"
      mgmt_config.vm.hostname = "mgmt"
      mgmt_config.vm.box_check_update = false
      # mgmt_config.vm.network "forwarded_port", guest: 80, host: 8080
      mgmt_config.vm.network "private_network", ip: "10.10.32.10"
      # mgmt_config.vm.network "public_network"
      # mgmt_config.vm.synced_folder "../data", "/vagrant_data"
      mgmt_config.vm.provider "virtualbox" do |vb|
         vb.memory = "256"
      end
      mgmt_config.vm.provision "shell", path: "mgmt_bootstrap.sh"
  end

  # web server
  #(1).each do |i|
  i = 1
  config.vm.define "web#{i}" do |node|
      node.vm.box = "ubuntu/trusty64"
      node.vm.hostname = "web#{i}"
      node.vm.box_check_update = false
      node.vm.network "forwarded_port", guest: 80, host: "808#{i}"
      node.vm.network "private_network", ip: "10.10.32.2#{i}"
      # node.vm.network "public_network"
      # node.vm.synced_folder "../data", "/vagrant_data"
      node.vm.provider "virtualbox" do |vb|
         vb.memory = "256"
      end
  end
  #end

end

