# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'
nodes = YAML.load_file('inf.yml')

Vagrant.configure(2) do |config|

  nodes.each do |nodes|
      config.vm.define nodes["name"] do |node|
          node.vm.box = nodes["box"]
          node.vm.hostname = nodes["name"]
          node.vm.box_check_update = nodes["check_updates"]
          node.vm.network nodes["net"], ip: nodes["ip"]
          if nodes["forward_host_port"] and nodes["forward_guest_port"]
            node.vm.network "forwarded_port", guest: nodes["forward_host_port"], host: nodes["forward_guest_port"]
          end
          node.vm.provider "virtualbox" do |vb|
             vb.memory = nodes["mem"]
          end
          if nodes["script"]
            node.vm.provision "shell", path: nodes["script"], privileged: false
          end
      end
  end

  # mon (Icinga Web 2 requires a second port to be forwarded.. looping over sets is not implemented atm)
  config.vm.define "mon" do |node|
      node.vm.box = "ubuntu/trusty64i"
      node.vm.hostname = "mon"
      node.vm.box_check_update = false
      node.vm.network "private_network", ip: "10.10.1.17"
      node.vm.network "forwarded_port", guest: 80, host: 11780
      node.vm.network "forwarded_port", guest: 5432, host: 5432
      node.vm.provider "virtualbox" do |vb|
         vb.memory = "256"
      end
  end
end

