---
icinga2:
  repos:
    - 'ppa:formorer/icinga'
  packages:
    - icinga2

icinga_web2:
  repos:
    - 'deb http://packages.icinga.org/ubuntu icinga-trusty main'
  packages:
    - php5-json
    - php5-gd
    - php5-imagick
    - php5-pgsql
    - php5-intl
    - php5-cli
    - php5-common
    - postgresql
    - python-psycopg2
    - icinga2-ido-pgsql
    - icingaweb2
  features:
    - command
    - ido-pgsql
  database:
    admin_user: postgres
    admin_password: postgres
    user: icingaweb2
    password: icingaweb2
    flags: SUPERUSER

