---
- name: restart Icinga 2
  become: yes
  become_method: sudo
  service: name=icinga2 state=restarted

- name: restart Apache
  become: yes
  become_method: sudo
  service: name=apache2 state=restarted
