---
- name: add Icinga 2 repo
  become: yes
  become_method: sudo
  apt_repository: repo={{ item }} state=present
  with_items:
    - "{{ icinga2.repos }}"
  tags:
    - icinga2

- name: install Icinga 2
  become: yes
  become_method: sudo
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - "{{ icinga2.packages }}"
  tags:
    - icinga2

- name: install Icinga Web 2 repo key
  become: yes
  become_method: sudo
  apt_key: url=http://packages.icinga.org/icinga.key state=present
  tags:
    - icinga_web2

- name: add Icinga Web 2 repo
  become: yes
  become_method: sudo
  apt_repository: repo={{ item }} state=present
  with_items:
    - "{{ icinga_web2.repos }}"
  tags:
    - icinga_web2

- name: install Icinga Web 2
  become: yes
  become_method: sudo
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - "{{ icinga_web2.packages }}"
  tags:
    - icinga_web2

- name: enable Icinga 2 features required by Icinga Web 2
  become: yes
  become_method: sudo
  shell: /usr/sbin/icinga2 feature enable {{ item }}
  with_items:
    - "{{ icinga_web2.features }}"
  tags:
    - icinga_web2
  notify:
    - restart Icinga 2

