---
- name: enable Icinga2 features
  become: yes
  become_method: sudo
  shell: /usr/sbin/icinga2 feature enable {{ item }}
  with_items:
    - "{{ icinga2.features }}"
  tags:
    - icinga2
  notify:
    - restart Icinga 2

- name: install Icinga Web 2 repo key
  become: yes
  become_method: sudo
  apt_key: url=http://packages.icinga.org/icinga.key state=present
  tags:
    - icinga_web2

- name: add Icinga Web 2 repo
  become: yes
  become_method: sudo
  apt_repository: repo='deb http://packages.icinga.org/ubuntu icinga-trusty main' state=present
#  with_items:
#    - "{{ repos }}"
  tags:
    - icinga_web2

- name: install Icinga Web 2
  become: yes
  become_method: sudo
  apt: name=icingaweb2 state=present update_cache=yes
#  with_items:
#    - "{{ packages }}"
  tags:
    - icinga_web2
